version: '3.8'
services:
  learning-management-service:
    build: .
    ports:
      - "8082:8082"
    #environment:
     # SPRING_PROFILES_ACTIVE=docker
     # SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/learning_db
      #EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:8761/eureka/
    depends_on:
      - mongo
    networks:
      - tutoring-network

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: learning_db
    networks:
      - tutoring-network

networks:
  tutoring-network:
    driver: bridge

volumes:
  mongo_data:
